wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.page, name="page"),
    path("search/", views.search, name="search"),
    path("create", views.createPage, name="createPage"),
    path("wiki/edit/<str:title>", views.editPage, name="editPage"),
    path("randompage", views.randomPage, name="randomPage")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
import random
import markdown2
from django.contrib import messages

from . import util

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def page(request, title):
    entryPage = util.get_entry(title)

    if entryPage is None:
         return render(request, "encyclopedia/errorPage.html", {
             "entryTitle": title
         })
    else:
        return render(request, "encyclopedia/page.html", {
            "entry": markdown2.markdown(util.get_entry(title)),
            "title": title
        })

def search(request):
    entries = util.list_entries()
    searchKey = request.GET.get("q")
    sub_list = []

    for entry in entries:
        if searchKey.lower() == entry.lower():
            return render(request, "encyclopedia/page.html", {
                "entry": markdown2.markdown(util.get_entry(searchKey)),
                "title": searchKey
            })
        elif searchKey.lower() in entry.lower():
            sub_list.append(entry)        

    if len(sub_list) > 0:
        return render(request, "encyclopedia/index.html",{
                "title":searchKey,
                "entries":sub_list
            })        
    else:
        messages.error(request, "No results found")
        return render(request, "encyclopedia/index.html")
            
def createPage(request):
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        searchEntry = util.get_entry(title)

        if searchEntry != None:
            messages.error(request, "This entry already exists")
            return render(request, "encyclopedia/createPage.html", {
                "title": title,
                "entries": util.list_entries()
            })
             
        else:
            util.save_entry(title, content)
            return render(request, "encyclopedia/page.html", {
                "entry": markdown2.markdown(util.get_entry(title)),
                "title": title
        })
    else:
        title = ""
        content = ""
        return render(request, "encyclopedia/createPage.html", {
            "entries": util.list_entries()
        })
    
def editPage(request, title):
    content = util.get_entry(title)

    if request.method == 'POST':
        content = request.POST.get('edit')
        util.save_entry(title, content)
        
        return render(request, "encyclopedia/page.html", {
            "entry": markdown2.markdown(util.get_entry(title)),
            "title": title
        })
    else :
        return render(request, "encyclopedia/editPage.html", {
            "entry": title,
            "content": content
        })
 
def randomPage(request):
    return render(request, "encyclopedia/randomPage.html", {
        "entries":  random.choice(util.list_entries())
    })
     

wiki/encyclopedia/templates/encyclopedia/createPage.html
{% extends "encyclopedia/layout.html" %}
 
{% block title %}
    Encyclopedia
{% endblock %}
 
{% block body %}

    <h1>Create new Wiki entry</h1>

    {% for message in messages %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
    {% endfor %}
             
    <form action="{% url 'encyclopedia:createPage' %}" method="post">
        {% csrf_token %}
        <input type="text" name="title" placeholder="Enter Title" required> <br>
        <textarea name="content" style="height: 60vh; width: 120vh; margin-top: 2vh;"
            placeholder="Insert content in Markdown language" required>{{ content }}</textarea><br>
        <button name="save" class="btn btn-primary" type="submit" style="align-items: center;">Create New Entry</button>
    </form> 
 
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry }}
{% endblock %}

{% block body %}

    <h1>Edit Page: {{ entry }} </h1>

    <form action="{% url 'encyclopedia:editPage' entry %}" method="POST" style="margin-top: 4vh;">
        {% csrf_token %} 
        <textarea name="edit" style="height: 60vh; width: 120vh;">{{ content }}</textarea><br>
        <button name="salvEdit" class="btn btn-primary" type="submit" style="align-items: center;">Save Changes</button>
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/errorPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1> Error 404 : Page Not Found </h1>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:page' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

    {% for message in messages %}
        <div>
            {{ message }}
        </div>
    {% endfor %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:createPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}
 
{% block title %}
    {{ title }}
{% endblock %}
 
{% block body %}
 
    <ul>
        {{ entries }}
    </ul>

    {{ entry|safe }}

    <a class="btn btn-primary" href="{% url 'encyclopedia:editPage' title %}">Edit Entry</a>
 
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/randomPage.html
{% extends "encyclopedia/layout.html" %}
 
{% block title %}
    Encyclopedia
{% endblock %}
 
{% block body %}
    <h1>Random</h1>
    <a href="{% url 'encyclopedia:page' entries %}">{{ entries }}</a>
{% endblock %}